### ISSUE TITLE
Ability to use the plugin with python version 3.9

### ISSUE THREAD

**Issue by akalagov** [Kani999/netbox-attachments#18]
It is currently only possible to use this plugin with python version 3.10 or higher, although most installations still use version 3.9. Is it possible to use the plugin with python version 3.9?

**Comment by Kani999** [comment]
@akalagov I did not try to use it with older versions. 
But could you test it out? 
Install the plugin from the branch `python_3_9` and let me know if it works.

`pip install git+https://github.com/Kani999/netbox-attachments.git@python_3_9`

**Comment by akalagov** [comment]
I tested the plugin with python 3.9 - it works without any problems and has no error or warning messages.

**Comment by Kani999** [comment]
> I tested the plugin with python 3.9 - it works without any problems and has no error or warning messages.
@akalagov Thanks for testing. The new version 1.0.5 should be released on PyPI in a minute and you can use it with python 3.9 now.

**Comment by akalagov** [comment]
Thank you for quickly resolving the issue!
