### ISSUE TITLE
Plugin breaks with netbox 3.4.0 release

### ISSUE THREAD

**Issue by akalagov** [Kani999/netbox-attachments#20]
When running the manage.py upgrade script from v3.3.10 to v.3.4.0 it fails with the output:
`django.core.exceptions.ImproperlyConfigured: Plugin netbox_attachments requires NetBox maximum version 3.3.99.`
Probably just need a version bump?

**Comment by Kani999** [comment]
@akalagov - Plugin looks fine at netbox 3.4.
I'll try it with netbox-docker in a minute, but I just released new version already.

**Comment by akalagov** [comment]
Yes, the plugin works great now, thanks!
