### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by advoenkin** [Kani999/netbox-attachments#32]
Hello, how i can increase max file size to upload? 

When i try ulpoad file with size 141 MB i got error "413 Request Entity Too Large".

**Comment by Kani999** [comment]
@advoenkin did the https://docs.netbox.dev/en/stable/configuration/miscellaneous/#file_upload_max_memory_size helped? 
Or it was at the side of web server (apache/nginx)

**Comment by advoenkin** [comment]
@Kani999 
I just change `client_max_body_size 200m;` in Nginx.
