### ISSUE TITLE
Missing instructions at install

### ISSUE THREAD

**Issue by johan-kummeneje-complior** [Kani999/netbox-attachments#35]
Hi, 
after some debugging it turned out that the directory for the attachments were needed to be manually created and chmodded to netbox user. 
That would be helpful to have in the installation instructions.

**Comment by Kani999** [comment]
I'll try to take a look at it. 
I'm using a netbox-docker installation. I will do a fresh installation and I try to reproduce the problem. 

I have no experience with installing netbox manually.

**Comment by MROSSFTEK** [comment]
where do you create this folder?
