### ISSUE TITLE
Short description and file name

### ISSUE THREAD

**Issue by advoenkin** [Kani999/netbox-attachments#36]
Hello, 

I have several suggestions:

1. Can you add short description for a file for show in table with files and file page? (Screen 1)
2. Can you hide path "netbox-attachments/" in Filename field at file page? I think display only file name will good.

![device](https://github.com/Kani999/netbox-attachments/assets/68369599/01cc7303-b5c0-4dae-bb39-100abaf5cdec)

**Comment by Kani999** [comment]
I'll take a look at it during next week.
