### ISSUE TITLE
You can no longer edit/delete the attachment once the parent has been deleted

### ISSUE THREAD

**Issue by whtkam** [Kani999/netbox-attachments#37]
You can no longer edit the attachment once the parent has been deleted. What would be good if you could still edit the attachment to define a new parent. Or that it is also possible to simply delete the attachment, which does not work either.

<class 'AttributeError'>
'NoneType' object has no attribute '_meta'

Python version: 3.9.11
NetBox version: 3.5.8
Plugins: 
  netbox_attachments: 2.0.1
  netbox_bgp: 0.10.2
  netbox_documents: 0.6.0
  netbox_ipcalculator: 1.1
  netbox_topology_views: 3.6.2

**Comment by Kani999** [comment]
I'll take a look at it during next week.

**Comment by Kani999** [comment]
This problem is the same as the #38 
Closing this ticket.
