### ISSUE TITLE
perfect for expanding other plugins usage

### ISSUE THREAD

**Issue by wols** [Kani999/netbox-attachments#46]
Thanks for this plugin!
I use attachments for delivery notes and invoices with [netbox-inventory](https://github.com/ArnesSI/netbox-inventory).

See my example [gist](https://gist.github.com/wols/06c1397c86d30b917bb5e955b6d4c0a5).

**Comment by Kani999** [comment]
Thanks!

I have create the wiki page with your link to gist. https://github.com/Kani999/netbox-attachments/wiki/Integration-with-netbox%E2%80%90inventory 

Your example looks pretty good.
