### ISSUE TITLE
Multiple device types

### ISSUE THREAD

**Issue by advoenkin** [Kani999/netbox-attachments#47]
Hello dear, 

Could you implement the ability, when adding a file, to select multiple types of devices to which this file belongs?

Thank you.

**Comment by Kani999** [comment]
Hello,
I don't think I'm able to do it.
The model for attachments is designed to be as general as possible.
So, I would need to figure out how to implement this feature across all the models in the core NetBox + plugins.

How would you envision this feature working?

**Comment by advoenkin** [comment]
Hello, I apologize for the long response.

I solved this feature using custom fields. I was create 3 custom fields with type "Selection" and using choice sets. Works perfect. Bu when i try using filters in http://url/plugins/netbox-attachments/netbox-attachments/ it's don't work. I always see all attachment list, but not filtered.

**Comment by Kani999** [comment]
@advoenkin - 
![image](https://github.com/Kani999/netbox-attachments/assets/17337078/07aec2e7-661f-479a-8e3b-582bc2cfc1f1)

You mean when you are using custom fields and filtering them through form above, it does not work?

**Comment by advoenkin** [comment]
@Kani999 Yes.

**Comment by Kani999** [comment]
@advoenkin problem should be fixed with a new release.
