### ISSUE TITLE
Ensure NetBox 4.0 compatibility

### ISSUE THREAD

**Issue by goebelmeier** [Kani999/netbox-attachments#59]
Currently netbox-attachments is breaking when installed on NetBox 4.0

`ModuleNotFoundError: No module named 'extras.plugins'`

Please see the dedicated [plugin migration guide](https://docs.netbox.dev/en/feature/plugins/development/migration-v4/) for a checklist of changes that may be needed to ensure compatibility with NetBox v4.0.

**Comment by Kani999** [comment]
Hello @goebelmeier,

The plugin isn't ready yet for NetBox v4.0. 
I'm planning to take a look at it next week.

**Comment by Kani999** [comment]
@goebelmeier 
I've released a beta version https://pypi.org/manage/project/netbox-attachments/release/5.0.0b1/ of netbox-attachments that supports NetBox v4

Could you test it out on a devel environment? 
I did not found any problem yet.

**Comment by goebelmeier** [comment]
Thank you! Will check next week, i'm on vacation until next week

**Comment by deanfourie1** [comment]
how can I install this, I will test.

**Comment by Kani999** [comment]
> how can I install this, I will test.

- Just specify the version in `plugin_requirements.txt` (netbox-docker) or `local_requirements.txt` (classic netbox installation) 
`netbox-attachments==5.0.0b1`
- Enable the plugin in `configuration.py:`
`PLUGINS = ['netbox_attachments']`

**Comment by deanfourie1** [comment]
Thanks, all is looking good for me.

However I cannot upload large files.

**Comment by Kani999** [comment]
I believe that setting of file size is based on configuration of your webserver and other stuff. 

 - See:
     - https://github.com/Kani999/netbox-attachments/issues/57 
     - https://github.com/netbox-community/netbox-docker/issues/897
     - Apache: https://stackoverflow.com/questions/74811649/how-to-increase-file-upload-size-in-apache-config
     - Nginx: https://docs.rackspace.com/docs/limit-file-upload-size-in-nginx

**Comment by goebelmeier** [comment]
Hi @Kani999 - looks good to me, working fine in my Netbox 4.0.2 testing environment. When do you plan to release it?

**Comment by Kani999** [comment]
@goebelmeier - Should be released right now.
