### ISSUE TITLE
Nested serializers are being deprecaded from netbox 4

### ISSUE THREAD

**Issue by matejv** [Kani999/netbox-attachments#65]
Netbox [plugin migration guide](https://netboxlabs.com/docs/netbox/en/stable/plugins/development/migration-v4/#extend-serializer-for-brief-mode) instructs plugin developers to remove Nested API serializers and add support for "brief" mode to regular serializers .

In netbox-inventory plugin I have done as the migration guide instructs and now users cannot use netbox-inventory with netbox-attachments. See [this issue](https://github.com/ArnesSI/netbox-inventory/issues/177#issuecomment-2230634489) for detailed description.

The problem originates [here](https://github.com/Kani999/netbox-attachments/blob/818ce2d501b151b1c7a8d36e324470812ddd8068/netbox_attachments/api/serializers.py#L48-L49) by calling `get_serializer_for_model` with prefix argument. 

You should probably change this to get a regular serializer and pass `brief=True` when calling it.

If you wanted to keep backward compatibility you could first try to get nested serializer as it is now and on `netbox.api.exceptions.SerializerNotFound` error get the regular serializer with `brief=True`.

I can submit a pull request if you'd like.

**Comment by Kani999** [comment]
I'll take a look at it, I also need to do some other changes.

**Comment by matejv** [comment]
Seems to work fine, thank you. I tested attachments on netbox_inventory.Asset (plugin) model and dcim.DeviceType.
