### ISSUE TITLE
Ensure Netbox 4.1 compatibility

### ISSUE THREAD

**Issue by goebelmeier** [Kani999/netbox-attachments#72]
Netbox 4.1 is live (https://github.com/netbox-community/netbox/releases/tag/v4.1.0) and the upgrade breaks, when netbox-attachments is installed:

https://github.com/Kani999/netbox-attachments/blob/52bff45ba57c1910affd4e6a4d84398e10bc51e7/netbox_attachments/__init__.py#L19

**Comment by Kani999** [comment]
I've generated 6.0.0-b1 release to enable installation. But I did not do any other changes yet. 
https://github.com/Kani999/netbox-attachments/releases/tag/6.0.0-b1 

The beta version is also released on pypi.
